FROM node:latest@sha256:f9a1756160a9e1c3dca456bc0b185bf8f2f112a6771c694df87288046f4306f1

RUN node --version && \
    npm --version

WORKDIR /opt/checkmarx-github-action

COPY package.json ./package.json
COPY src ./src
COPY action.yml ./action.yml
COPY README.md ./README.md
COPY LICENSE ./LICENSE

RUN npm install

CMD [ "node", "src/index.js" ]