name: 2020.2.18 OSA Scan
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
    - name: Checkmarx Action
      uses: ./
      with:
        cxAction: OsaScan
        cxServer: ${{ secrets.CX_OSA_SERVER }}
        cxUsername: ${{ secrets.CX_OSA_EMAIL }}
        cxPassword: ${{ secrets.CX_OSA_PASSWORD }}
        cxTeam: ${{ secrets.CX_OSA_TEAM }}
        cxExecutePackageDependency: true
        cxVersion: "2020.2.18"
        cxLog: log.log
        cxGithubIssues: true
        cxGithubToken: ${{ secrets.GITHUB_TOKEN }}
        cxGithubLabels: bug,test
        cxGithubAssignees: miguelfreitas93
    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        name: log.log
        path: log.log
